# Generated by Django 3.0.5 on 2020-04-13 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memmem_app', '0002_auto_20200413_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Scrap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True)),
                ('folder_name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('url', models.URLField()),
            ],
        ),
        migrations.RenameModel(
            old_name='UserModel',
            new_name='User',
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to='')),
                ('folder_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memmem_app.Folder')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memmem_app.Scrap')),
            ],
        ),
        migrations.AddField(
            model_name='folder',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memmem_app.User'),
        ),
    ]
