# Generated by Django 3.0.5 on 2020-04-18 10:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('memmem_app', '0003_auto_20200414_0123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='scrap',
            name='folder_name',
        ),
        migrations.AddField(
            model_name='folder',
            name='user',
            field=models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='memmem_app.User'),
        ),
        migrations.AddField(
            model_name='scrap',
            name='folder',
            field=models.ForeignKey(default='default', max_length=50, on_delete=django.db.models.deletion.CASCADE, to='memmem_app.Folder'),
        ),
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
