# Generated by Django 3.0.5 on 2020-04-18 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memmem_app', '0004_auto_20200418_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='folder_name',
        ),
        migrations.RemoveField(
            model_name='list',
            name='title',
        ),
        migrations.RemoveField(
            model_name='scrap',
            name='folder',
        ),
        migrations.DeleteModel(
            name='Folder',
        ),
        migrations.DeleteModel(
            name='List',
        ),
        migrations.DeleteModel(
            name='Scrap',
        ),
    ]
